#OPTIMIZATION
##FUCTIONS
####get.trim.df.LOSTA
```{R}
# Compare to groundtruth
# For all ATCG predict tools
# 1448A chromosome, large plasmid and small plasmid have 1.22e7 nt in both strands

# for mCaller, Dorado, they are singel mode and A only, so the don't need shift
# for single mode, they need to find the LOST sites of WT when compare to KO
get.trim.df.LOSTA <- function(preds_WT, preds_KO, gt_df) {
  TP1 <- c()
  FN1 <- c() 
  FP1 <- c()
  TN1 <- c()
  TPR1 <- c()
  TNR1 <- c()
  FPR1 <- c()
  precision1 <- c()
  recall1 <- c()
  F1score1 <- c()
  rank1 <- c()
  originalvalue1 <- c()
  value1 <- c()
  
  cutoffs <- seq(log10(1), log10(2.573e6), length.out = 200) # for ATCG
  cutoffs <- 10^cutoffs
  
  
  for (cutoff in cutoffs) {
    print(cutoff)
    preds_WT_temp <- subset(preds_WT, Rank <= cutoff) # if it is rank, make sure <=; if it is fraction, make sure >=
    preds_KO_temp <- subset(preds_KO, OriginalValue >= min(preds_WT_temp$OriginalValue))
    preds <- anti_join(preds_WT_temp, preds_KO_temp, by = c("Position", "Chromosome", "Strand"))
    rank1 <- c(rank1,nrow(preds_WT_temp))
    value1 <- c(value1,min(preds_WT_temp$Value))
    originalvalue1 <- c(originalvalue1,min(preds_WT_temp$OriginalValue))
    
    intersection <- inner_join(preds, gt_df, by = c("Position", "Chromosome", "Strand"))
    TP <- nrow(intersection)
    TP1 <- c(TP1,TP)
    union <- rbind(preds,gt_df)
    union <- union[!duplicated(union[, c("Position", "Chromosome", "Strand")]), ]
    diff <- anti_join(Asites, union, by = c("Position", "Chromosome", "Strand"))
    TN <- nrow(diff)
    TN1 <- c(TN1,TN)
    FP = nrow(preds)-TP
    FP1 <- c(FP1,FP)
    FN = nrow(gt_df)-TP
    FN1 <- c(FN1,FN)
    precision = TP/nrow(preds)
    precision1 <- c(precision1, precision)
    recall = TP/nrow(gt_df)
    recall1 <- c(recall1, recall)
    F1score = 2*precision*recall/(precision+recall)
    F1score1 <- c(F1score1,F1score)
    TPR1 <- c(TPR1, TP/(TP+FN))
    TNR1 <- c(TNR1, TN/(TN+FP))
    FPR1 <- c(FPR1, FP/(FP+TN))
  }
  plot1 <- data.frame(Cutoff = cutoffs, Rank = rank1, Value = value1, OriginalValue = originalvalue1, TP = TP1, FN = FN1, FP = FP1, TN = TN1, Precision = precision1, Recall = recall1, F1score = F1score1, TPR = TPR1, TNR = TNR1, FPR = FPR1) 
  return(plot1)
} 

```


####get.trim.df.LOSTATCG
```{R}
# for mCaller, Dorado, they are singel mode and A only, so the don't need shift
# for single mode, they need to find the LOST sites of WT when compare to KO
get.trim.df.LOSTATCG <- function(preds_WT, preds_KO, gt_df) {
  
  gt_df_5mer <- get.5mer.df(gt_df)
  
  TP1 <- c()
  FN1 <- c() 
  FP1 <- c()
  TN1 <- c()
  TPR1 <- c()
  TNR1 <- c()
  FPR1 <- c()
  precision1 <- c()
  recall1 <- c()
  F1score1 <- c()
  rank1 <- c()
  originalvalue1 <- c()
  value1 <- c()
  
  cutoffs <- seq(log10(1), log10(1.223e7), length.out = 200) # for ATCG
  cutoffs <- 10^cutoffs
  
  for (cutoff in cutoffs) {
    print(cutoff)
    preds_WT_temp <- subset(preds_WT, Rank <= cutoff) # if it is rank, make sure <=; if it is fraction, make sure >=
    preds_KO_temp <- subset(preds_KO, OriginalValue >= min(preds_WT_temp$OriginalValue))
    preds <- anti_join(preds_WT_temp, preds_KO_temp, by = c("Position", "Chromosome", "Strand"))
    rank1 <- c(rank1,nrow(inner_join(preds_WT_temp, Asites, by = c("Chromosome","Position","Strand"))))
    value1 <- c(value1,min(preds_WT_temp$Value))
    originalvalue1 <- c(originalvalue1,min(preds_WT_temp$OriginalValue))
    intersection1 <- inner_join(preds, gt_df_5mer, by = c('Position','Chromosome','Strand'))
    TP_precision = nrow(intersection1)
    TP1 <- c(TP1,TP_precision)
    FP = nrow(preds)-TP_precision
    FP1 <- c(FP1,FP)
    
    union <- rbind(preds,gt_df)
    union <- union[!duplicated(union[, c("Position", "Chromosome", "Strand")]), ]
    diff <- anti_join(Asites, union, by = c("Position", "Chromosome", "Strand"))
    TN <- nrow(diff)
    TN1 <- c(TN1,TN)
    
    b <- get.5mer.df(preds)
    intersection2 <- inner_join(b, gt_df, by = c('Position','Chromosome','Strand'))
    TP_recall = nrow(intersection2)
    FN = nrow(gt_df)-TP_recall
    FN1 <- c(FN1,FN)
    precision = TP_precision/nrow(preds)
    precision1 <- c(precision1, precision)
    recall = TP_recall/nrow(gt_df)
    recall1 <- c(recall1, recall)
    F1score = 2*precision*recall/(precision+recall)
    F1score1 <- c(F1score1,F1score)
    TPR1 <- c(TPR1, TP_precision/(TP_precision+FN))
    TNR1 <- c(TNR1, TN/(TN+FP))
    FPR1 <- c(FPR1, FP/(FP+TN))
  }
  plot1 <- data.frame(Cutoff = cutoffs, Rank = rank1, Value = value1, OriginalValue = originalvalue1, TP = TP1, FN = FN1, FP = FP1, TN = TN1, Precision = precision1, Recall = recall1, F1score = F1score1, TPR = TPR1, TNR = TNR1, FPR = FPR1) 
  return(plot1)
}  
```


Get trimed.df and draw F1 score
## trimed.df.op.WT calculated
```{r}
dataset.name <- c("SMRT", "Dorado",  "mCaller", "Tombo_denovo", "Tombo_levelcom", "Tombo_modelcom")
trimed.df.OP.WT <-data.frame()

for (name in dataset.name){
  print(name)
  # get file
  df_WT <- get(name)
  df_WGA <- get(paste0(name, "_WGA"))
  if (name == "mCaller" | name == "Dorado" | name == "SMRT"){
    trimed_temp <-  get.trim.df.LOSTA(df_WT, df_WGA, Motifs)
    trimed.df.OP.WT <- rbind(trimed.df.OP.WT, data.frame(Tool = name, as.data.frame(trimed_temp)))
  }
  else{
    # Tombo_denovo and Hammerhead, they are ATCG and single mode, shift and 1.2e7 cutoffs
    trimed_temp <-  get.trim.df.LOSTATCG(df_WT, df_WGA, Motifs)
    trimed.df.OP.WT <- rbind(trimed.df.OP.WT, data.frame(Tool = name, as.data.frame(trimed_temp)))
  }
  rm(trimed_temp)
  trimed.df.OP.WT[is.na(trimed.df.OP.WT)] <- 0
}
  

write.csv(trimed.df.OP.WT,"/Users/lubeifang/Desktop/Benchmark/intermediateFILE/1448AOP_WT.trimed.df1114.csv")
```

## trimed.df.op.MU calculated
```{r}
trimed.df.OP.MU <- data.frame()
dataset.name <- c("SMRT")
for (name in dataset.name){
  print(name)
  # get file
  df_MU <- get(paste0(name, "_MU"))
  df_WGA <- get(paste0(name, "_WGA"))
  if (name == "mCaller" | name == "Dorado"){
    trimed_temp <-  get.trim.df.LOSTA(df_MU, df_WGA, MotifT2)
    trimed.df.OP.MU <- rbind(trimed.df.OP.MU, data.frame(Tool = name, as.data.frame(trimed_temp)))
  }
  else{
    # Tombo_denovo and Hammerhead, they are ATCG and single mode, shift and 1.2e7 cutoffs
    trimed_temp <-  get.trim.df.LOSTATCG(df_MU, df_WGA, MotifT2)
    trimed.df.OP.MU <- rbind(trimed.df.OP.MU, data.frame(Tool = name, as.data.frame(trimed_temp)))
  }
  rm(trimed_temp)
  trimed.df.OP.MU[is.na(trimed.df.OP.MU)] <- 0
}
  

write.csv(trimed.df.OP.MU,"/Users/lubeifang/Desktop/Benchmark/intermediateFILE/1448AOP_MU.trimed.df1114.csv",row.names = F)
```

## plot figures
### F1 score
```{R}
trimed.df.OP.WT <- read.csv("/Users/lubeifang/Desktop/Benchmark/intermediateFILE/1448AOP_WT.trimed.df1001.csv", row.names = 1)
# plot F1 score curve
p <- ggplot(trimed.df.OP.WT, aes(x=Rank, y=F1score, group=Tool, color=Tool))+
  geom_line(size=0.8) +
  ggtitle("1448AOP_WT F1 score") +
  theme_light() +
  xlab("A sites") +
  theme(
    panel.border = element_rect(color = "black", fill = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_blank(),
    # axis.text.x = element_text(family = "Arial", size = 10),
    # axis.text.y = element_text(family = "Arial", size = 10),
    legend.position="none"
  ) +
  scale_color_manual(values = c("#98B85D","#AC667E","#B395BD","#287c9e","#a9a9a9","#e29578"))

pp <- ggplot(trimed.df.OP.WT, aes(x=Rank, y=F1score, group=Tool, color=Tool))+
  geom_line(size=0.5) +
#  geom_point(size = 0.2, color = "grey") +
  theme_bw() +
  theme(legend.position="none")+
  scale_color_manual(values = c("#98B85D","#AC667E","#B395BD","#287c9e","#a9a9a9","#e29578")) +
    xlim(0,20000)+
  xlab("")+
  ylab("")
p1 <- p + inset_element(pp, left = 0.3, bottom = 0.3, right = 0.95, top = 0.95) 
p1


trimed.df.OP.MU <- read.csv("/Users/lubeifang/Desktop/Benchmark/intermediateFILE/1448AOP_MU.trimed.df1114.csv")

# plot F1 score curve
p <- ggplot(trimed.df.OP.MU, aes(x=Rank, y=F1score, group=Tool, color=Tool))+
  geom_line(size=0.8) +
  ggtitle("1448AOP_MU F1 score") +
  theme_light() +
  xlab("A sites") +
  theme(
    panel.border = element_rect(color = "black", fill = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_blank(),
    # axis.text.x = element_text(family = "Arial", size = 10),
    # axis.text.y = element_text(family = "Arial", size = 10),
    legend.position="bottom"
  ) +
  scale_color_manual(values = c("#98B85D","#AC667E","#B395BD","#287c9e","#a9a9a9","#e29578")) 

pp <- ggplot(trimed.df.OP.MU, aes(x=Rank, y=F1score, group=Tool, color=Tool))+
  geom_line(size=0.5) +
#  geom_point(size = 0.2, color = "grey") +
  theme_bw() +
  theme(legend.position="none")+
  scale_color_manual(values = c("#98B85D","#AC667E","#B395BD","#287c9e","#a9a9a9","#e29578"))  +
    xlim(0,20000)+
  xlab("")+
  ylab("")
p2 <- p + inset_element(pp, left = 0.3, bottom = 0.3, right = 0.95, top = 0.95) 
p2

plot <- p1+p2
ggsave("/Users/lubeifang/Desktop/Benchmark/Figure/F5_OP/1448AOP1114.pdf", plot, width = 7, height = 4.5)
```


### heat map
```{R}
trimed.df.WT<-read.csv("/Users/lubeifang/Desktop/Benchmark/intermediateFILE/1448AWT.trimed.df1113.csv")
trimed.df.MU<-read.csv("/Users/lubeifang/Desktop/Benchmark/intermediateFILE/1448AMU.trimed.df1114.csv",row.names = 1)
dataset.name <- c("SMRT", "Dorado",  "mCaller", "Tombo_denovo", "Tombo_levelcom", "Tombo_modelcom")
trimset.name <- c("trimed.df.WT", "trimed.df.OP.WT" , "trimed.df.MU", "trimed.df.OP.MU")

best.df <- data.frame()

# Give a dataframe of best F1 with cutoff
for (i in trimset.name){
  df <- get(i)
  for (k in dataset.name){
    # Get the row of best F1 score
    df.cate <- subset(df, Tool == k)
    df.cate <- subset(df.cate,F1score == max(df.cate$F1score))
    best.df.temp <- df.cate[order(df.cate$OriginalValue, decreasing = F),][1,]
    best.df.temp <- cbind(Type = "BestF1", best.df.temp)
    best.df <- rbind(best.df, data.frame(trimset = i, as.data.frame(best.df.temp)))
  }
}
rm(best.df.temp, df.cate)

AUC <- data.frame()
for (k in trimset.name ){
  trimed.df<-get(k)
  for (i in dataset.name){
    area_PR <- get.auc(i, "Recall", "Precision")
    area_ROC <- get.auc(i, "FPR", "TPR")
    AUC <- rbind(AUC, data.frame(set=k,name = i, PRC = round(area_PR[["value"]],3), ROC = round(area_ROC[["value"]],3)))
  }
}

best <- cbind(best.df,AUC)

best$trimset <- gsub("trimed.df.WT","trimed.df1",best$trimset)
best$trimset <- gsub("trimed.df.OP.WT","trimed.df2",best$trimset)
best$trimset <- gsub("trimed.df.MU","trimed.df3",best$trimset)
best$trimset <- gsub("trimed.df.OP.MU","trimed.df4",best$trimset)


p1 <- ggplot(best, aes(trimset, Tool, fill= F1score,label=round(F1score,3))) + 
  geom_tile() +
  theme_bw() +
  scale_fill_distiller(palette = "GnBu", trans = "reverse") +
  scale_y_discrete(limits = rev(dataset.name)) +
  xlab("") +
  ylab("") +
  geom_tile(alpha = 0.5) + 
  geom_text() +
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45,vjust=0.5,hjust=0.5))

p2 <- ggplot(best, aes(trimset, Tool, fill= Value,label=round(Value,3))) + 
  geom_tile() +
  theme_bw() +
  scale_fill_distiller(palette = "GnBu", trans = "reverse") +
  scale_y_discrete(limits = rev(dataset.name)) +
  xlab("") +
  ylab("") +
  geom_text() +
  theme(legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45,vjust=0.5,hjust=0.5))

p3 <- ggplot(best, aes(trimset, Tool, fill= Precision, label=round(Precision,3))) + 
  geom_tile() +
  theme_bw() +
  scale_fill_distiller(palette = "GnBu", trans = "reverse") +
  scale_y_discrete(limits = rev(dataset.name)) +
  xlab("") +
  ylab("") +
  geom_text() +
  theme(legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45,vjust=0.5,hjust=0.5))

p4 <- ggplot(best, aes(trimset, Tool, fill= FPR,label=round(FPR,3))) + 
  geom_tile() +
  theme_bw() +
  scale_fill_distiller(palette = "GnBu", trans = "reverse") +
  scale_y_discrete(limits = rev(dataset.name)) +
  xlab("") +
  ylab("") +
  geom_text() +
  theme(legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45,vjust=0.5,hjust=0.5))

p <- p1|p2|p3|p4
ggsave("/Users/lubeifang/Desktop/Benchmark/Figure/F5_OP/heat1104.pdf",width = 13, height = 5)


```

```{R}
p1 <- ggplot(best, aes(trimset, Tool, fill= Rank,label=round(Rank,3))) + 
  geom_tile() +
  theme_bw() +
  scale_fill_distiller(palette = "GnBu", trans = "reverse") +
  scale_y_discrete(limits = rev(dataset.name)) +
  xlab("") +
  ylab("") +
  geom_tile(alpha = 0.5) + 
  geom_text() +
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45,vjust=0.5,hjust=0.5))

p2 <- ggplot(best, aes(trimset, Tool, fill= Recall,label=round(Recall,3))) + 
  geom_tile() +
  theme_bw() +
  scale_fill_distiller(palette = "GnBu", trans = "reverse") +
  scale_y_discrete(limits = rev(dataset.name)) +
  xlab("") +
  ylab("") +
  geom_text() +
  theme(legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45,vjust=0.5,hjust=0.5))

p3 <- ggplot(best, aes(trimset, Tool, fill= TPR, label=round(TPR,3))) + 
  geom_tile() +
  theme_bw() +
  scale_fill_distiller(palette = "GnBu", trans = "reverse") +
  scale_y_discrete(limits = rev(dataset.name)) +
  xlab("") +
  ylab("") +
  geom_text() +
  theme(legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45,vjust=0.5,hjust=0.5))

p4 <- ggplot(best, aes(trimset, Tool, fill= TNR,label=round(TNR,3))) + 
  geom_tile() +
  theme_bw() +
  scale_fill_distiller(palette = "GnBu", trans = "reverse") +
  scale_y_discrete(limits = rev(dataset.name)) +
  xlab("") +
  ylab("") +
  geom_text() +
  theme(legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45,vjust=0.5,hjust=0.5))

p <- p1|p2|p3|p4
ggsave("/Users/lubeifang/Desktop/Benchmark/Figure/F5_OP/heat2.pdf",width = 13, height = 5)


```
